version: '3'

services:
    prometheus:
        image: prom/prometheus
        volumes:
            - './prometheus.yml:/etc/prometheus/prometheus.yml'
        networks:
            - host-net
        ports:
            - 9090:9090

    node-exporter:
        image: prom/node-exporter
        networks:
            - host-net
        ports:
            - 9100:9100

networks:
    host-net:
        external: true
