version: '3.7'

networks:
    host-net:
        external: true

services:
    vector:
        image: timberio/vector:0.34.2-alpine
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./vector.yaml:/etc/vector/vector.yaml
        networks:
            - host-net
